[project]
name = "pipenv-poetry-migrate-project"
description = "Utility for migrating Pipenv to Poetry"
authors = [{ name = "Yoshiyuki Hino", email = "yhinoz@gmail.co" }]
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
dependencies = [
  "pipenv-poetry-migrate",
  "poetry"
]
dynamic = ["version"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
keywords = ["pipenv", "poetry", "migration", "dependency", "pyproject.toml"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } }
]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }
