FROM alpine:3.16.1@sha256:7580ece7963bfa863801466c0a488f11c86f85d9988051a9f9c68cb27f6b7872 AS build

ARG BUILD_VERSION

RUN test -n "${BUILD_VERSION}" \
	&& apk update \
	&& apk add --no-cache ca-certificates bash curl make git gcc \
	&& update-ca-certificates 

RUN gcc -v

HEALTHCHECK NONE
