FROM ubuntu:24.04@sha256:5b582c80ed6832665ffb6181ab4d3e5e70c30c2548fbcea1de8a0a51f161be8d

ARG BUILD_VERSION
ARG ARCHIVE_URL=https://dl.dell.com/FOLDER08713913M/1/pstcli-${BUILD_VERSION}.x86_64.release.rpm

RUN test -n "${BUILD_VERSION}" \
	&& apt-get update \
	&& apt-get -y dist-upgrade \
	&& DEBIAN_FRONTEND=${DEBIAN_FRONTEND} apt-get install -y --no-install-recommends ca-certificates curl alien \
	&& curl -O "${ARCHIVE_URL}" \
	&& alien -i pstcli-${BUILD_VERSION}.x86_64.release.rpm \
	&& apt-get -y purge wget alien \
	&& apt-get -y autoclean \
	&& apt-get -y autoremove --purge 

# EXPOSE
# ENV
# STOPSIGNAL
HEALTHCHECK NONE
USER nobody

ENTRYPOINT ["pstcli"]
