[project]
name = "openbb-cli-project"
version = "1.1.9"
#dynamic = ["version"]
description = "OpenBB Platform CLI"
readme = "README.md"
authors = [{ name = "OpenBB", email = "hello@openbb.co" }]
requires-python = ">=3.12"
dependencies = [
  "openbb",
  "openbb-cli",
  "grpcio",
  "langchain",
  "tornado",
  "wheel"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } }
]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }

[dependency-groups]
dev = []

[tool.pip-tools]
generate-hashes = false
