FROM ghcr.io/jauderho/alpine:3.20.1@sha256:7be2d5bc23d77fca3910abe49334a98c19240510dc642a20a829b3bafa3b740d AS build

ARG BUILD_VERSION

RUN test -n "${BUILD_VERSION}" \
	&& apk update \
	&& apk add --no-cache ca-certificates bash curl make git gcc \
	&& update-ca-certificates 

RUN gcc -v

HEALTHCHECK NONE
