FROM ghcr.io/jauderho/alpine:3.21.3@sha256:4d30faf9002da9de8e2b91f6c1fadd20d55377434596e161fa014a72a3cf4dd1 AS build

ARG BUILD_VERSION

RUN test -n "${BUILD_VERSION}" \
	&& apk update \
	&& apk add --no-cache ca-certificates bash curl make git gcc \
	&& update-ca-certificates 

RUN gcc -v

HEALTHCHECK NONE
