[project]
name = "shell-gpt-project"
dynamic = ["version"]
description = "Project using shell_gpt from Git"
authors = [{ name = "Jauder Ho" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
keywords = ["shell_gpt", "cli", "openai", "chatgpt"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "shell_gpt @ git+https://github.com/TheR1D/shell_gpt.git",
  "typer",
  "requests",
  "rich"
]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true } }]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }
