[project]
name = "posting-project"
description = "A powerful HTTP client that lives in your terminal."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "Apache Software License" }
authors = [
  { name = "Darren Burns", email = "darrenb900@gmail.com" }
]
dependencies = [
  "posting",
  "rich",
  "pyyaml",
  "prompt_toolkit",
  "httpx[brotli]",
  "pygments",
  "python-dateutil",
  "click",
  "urwid",
  "pyperclip",
  "colorama",
  "requests",
  "certifi",
  "chardet",
  "idna",
  "urllib3"
]
keywords = ["http", "client", "terminal", "tui", "postman", "insomnia"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.13",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Terminals"
]
dynamic = ["version"]

[tool.uv]
index-url = "https://pypi.org/simple"
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } }
]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }

[dependency-groups]
dev = []
