[project]
name = "codespell-env"
version = "0.1.0"
description = "Environment for codespell"
requires-python = ">=3.0"
dependencies = [
    "codespell",
]

[tool.uv]
index-url = "https://pypi.org/simple"
#extra-index-url = ["https://www.piwheels.org/simple"]
