[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlx-project"
#dynamic = ["version"]
version = "1.0.0"
description = "A command line tool for downloading and managing MLX models"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT License"}
authors = [
    {name = "Gaurav Aggarwal", email = "gauravaggarwal@mail.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = [
    #"mlx@git+https://github.com/ml-explore/mlx",
    "mlx",
    #"setuptools>=42",
    #"nanobind>=2.1.0",
    #"cmake>=3.24",
]

[project.urls]
Homepage = "https://github.com/ml-explore/mlx"

[project.scripts]
mlx-hub-cli = "mlx_hub.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"mlx_hub" = ["data/*.txt"]

[tool.setuptools.dynamic]
version = {attr = "mlx_hub.__version__"}
