[project]
name = "scrapeghost-project"
description = "Structured scraping with LLMs, including schema definition, extraction, and parsing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "scrapeghost"
]
dynamic = ["version"]
authors = [
  { name = "Jason Liu", email = "jasonliu@posteo.net" }
]
license = { text = "MIT" }
keywords = ["scraping", "web scraping", "structured extraction", "llm", "langchain", "schema"]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12"
]

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } }
]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }

[dependency-groups]
dev = []
