[project]
name = "prowler-project"
description = "AWS, GCP, and Azure security assessment tool."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "prowler",
  "httpx[http2]",
]
dynamic = ["version"]

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { git = { commit = true, tags = true } }
]

[tool.uv.sources]
pypi = { url = "https://pypi.org/simple" }

[dependency-groups]
dev = []
