# Set the base image
#FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1809 AS base
FROM mcr.microsoft.com/windows/nanoserver:1809
#FROM mcr.microsoft.com/windows:10.0.19042.1469
WORKDIR /app
EXPOSE 80

