name: 'Dependency Review'
on: 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: 'Checkout Repository'
        uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3f943b86c9a289f4e632c632695e2e0898d9d67d
