# https://dev.to/brunorobert/github-and-gitlab-sync-44mn
# This pushes code from GitHub to Gitlab upon commit to GH
name: Gitlab Sync

on:
  - push
  - delete

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
      with:
        egress-policy: audit
        allowed-endpoints: 
          github.com:443
          gitlab.com:443
        
    - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      with:
        fetch-depth: 0
        
    - uses: jauderho/git-repo-sync@63782025e80e84c48b25a1ee6bb9a22a3bd570d3 # v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        #target-url: ${{ secrets.GITLAB_URL }}
        target-url: https://gitlab.com/${{ github.repository }}.git
        # Such as wangchucheng
        #target-username: ${{ secrets.GITLAB_USERNAME }}
        target-username: ${{ github.actor }}
        # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.GITLAB_TOKEN }}
