name: pingcastle

on:
  push:
    branches: 
      - main
    paths:
      - pingcastle/*
      - .github/workflows/pingcastle.yml
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  BUILD_VERSION: "2.10.1.0"
  DOCKER_CLI_EXPERIMENTAL: enabled
  REPOSITORY: ${{ github.actor }}/${{ github.workflow }} 

jobs:

  deploy:
    runs-on: windows-2022

    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0 
 
      - name: GitHub login
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: DockerHub login
#        if: ${{ github.event_name != 'pull_request' }}
#        uses: docker/login-action@v1.12.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}      

      - name: Build and push
        run: |
          docker build --file=${{ github.workflow }}/Dockerfile -t ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }} -t ghcr.io/${{ env.REPOSITORY }}:latest .
          docker push ghcr.io/${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
          docker push ghcr.io/${{ env.REPOSITORY }}:latest

