name: Test
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.17.6

jobs:
  lint:
    name: Hashtest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0
        
      - name: Get Go commit short hash
        id: shorthash
        #run: git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}' | head -c 8
        run: echo "::set-output name=hash::$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}' | head -c 8)"
      
      - name: Print the output
        run: echo "${{ steps.shorthash.outputs.hash }}"
