name: Test
on: 
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: 1.21.0
  UPSTREAM_REPO: https://github.com/golang/go.git

permissions: read-all

jobs:
  lint:
    name: Hashtest
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Check out code into the Go module directory
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v2.4.0
        
      - name: Get commit short hash from remote repo
        id: get-hash
        #run: git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}' | head -c 8
        #run: echo "::set-output name=hash::$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}' | head -c 8)"
        #run: echo "::set-output name=hash::$(git ls-remote ${{ env.UPSTREAM_REPO }} HEAD | awk '{print $1}' | head -c 8)"
        #run: echo "::set-output name=hash::$(git ls-remote ${{ env.UPSTREAM_REPO }} HEAD | cut -f1 | head -c 8)"
        run: echo "hash=$(git ls-remote ${{ env.UPSTREAM_REPO }} HEAD | awk '{print $1}' | head -c 8)" >> $GITHUB_OUTPUT
      
      - name: Print the output
        run: echo "${{ steps.get-hash.outputs.hash }}"

        # https://pakstech.com/blog/github-actions-workflow-commands/
      - name: Print the output (using env variable)
        run: echo "$HASH"
        env:
          HASH: ${{ steps.get-hash.outputs.hash }}
